import {
	CREDIT_CARDS,
	PRICE_TABLES,
	PRODUCT_CARD,
	PROFILE_CARD,
	QR_CODE_COMPONENT,
	RESPONSIVE_HERO,
	SMARTWATCH_INTERFACE
} from './challenges/html-css';

import {
	ADVANCED_PASSWORD_GENERATOR,
	BLACK_PLATE,
	GUESS_THE_NUMBER,
	SIMPLE_PASSWORD_GENERATOR
} from './challenges/javascript';

export const CHALLENGES = [
	GUESS_THE_NUMBER,
	CREDIT_CARDS,
	PROFILE_CARD,
	QR_CODE_COMPONENT,
	SIMPLE_PASSWORD_GENERATOR,
	PRODUCT_CARD,
	PRICE_TABLES,
	ADVANCED_PASSWORD_GENERATOR,
	RESPONSIVE_HERO,
	BLACK_PLATE,
	SMARTWATCH_INTERFACE
];
